version: '3.7'

networks:
  open-notifier-network:
    name: open-notifier-network
    driver: bridge

services:
  open-notifier-db:
    image: postgres:14-bullseye
    container_name: open-notifier-db
    restart: always
    networks:
      - open-notifier-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=open_notifier
  
  open-notifier-redis:
    image: redis:latest
    container_name: open-notifier-redis
    networks:
      - open-notifier-network
    restart: always
  
  open-notifier-service:
    build:
      context: ./
    container_name: open-notifier-service
    networks:
      - open-notifier-network
    environment:
      - APP_TYPE=service
    ports:
      - 8050:8050
    depends_on:
      - "open-notifier-db"
      - "open-notifier-redis"

  open-notifier-celery:
    build:
      context: ./
    container_name: open-notifier-celery
    networks:
      - open-notifier-network
    environment:
      - APP_TYPE=celery
    depends_on:
      - "open-notifier-db"
      - "open-notifier-redis"
