networks:
  enotifier-network:
    name: enotifier-network
    driver: bridge

services:
  enotifier-db:
    image: postgres:17
    container_name: enotifier-db
    restart: always
    networks:
      - enotifier-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=enotifier
  
  enotifier-redis:
    image: redis:latest
    container_name: enotifier-redis
    networks:
      - enotifier-network
    restart: always
  
  enotifier-service:
    build:
      context: ./
    container_name: enotifier-service
    networks:
      - enotifier-network
    environment:
      - APP_TYPE=service
    ports:
      - 8050:8050
    depends_on:
      - "enotifier-db"
      - "enotifier-redis"
    restart: always
    
  enotifier-grpc:
    build:
      context: ./
    container_name: enotifier-grpc
    networks:
      - enotifier-network
    environment:
      - APP_TYPE=grpc
    ports:
      - 50080:50080
    depends_on:
      - "enotifier-db"
      - "enotifier-redis"
    restart: always

  enotifier-celery:
    build:
      context: ./
    container_name: enotifier-celery
    networks:
      - enotifier-network
    environment:
      - APP_TYPE=celery
    depends_on:
      - "enotifier-db"
      - "enotifier-redis"
    restart: always

  enotifier-socketio:
    build:
      context: ./
    container_name: enotifier-socketio
    networks:
      - enotifier-network
    ports:
      - 8151:8151
    environment:
      - APP_TYPE=socketio
    depends_on:
      - "enotifier-db"
      - "enotifier-redis"
    restart: always
