# Generated by Django 4.1.1 on 2022-10-07 06:34

from django.db import migrations, models
import django.utils.timezone
import unixtimestampfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True, default=django.utils.timezone.now)),
                ('modified_on', unixtimestampfield.fields.UnixTimeStampField(auto_now=True, default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('modified_by', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tenants',
            },
        ),
    ]
