# Generated by Django 4.1.7 on 2023-05-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templates", "0002_template_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="notification_type",
            field=models.CharField(
                choices=[("EMAIL", "EMAIL"), ("WHATSAPP", "WHATSAPP")],
                default="EMAIL",
                max_length=50,
            ),
        ),
    ]
