# Generated by Django 4.1.7 on 2023-05-04 08:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templates", "0003_alter_template_notification_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="template",
            name="notification_type",
        ),
        migrations.AddField(
            model_name="template",
            name="notification_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("EMAIL", "EMAIL"),
                        ("WHATSAPP", "WHATSAPP"),
                        ("SMS", "SMS"),
                    ],
                    default="EMAIL",
                    max_length=50,
                ),
                default=["EMAIL"],
                size=None,
            ),
        ),
    ]
