# Generated by Django 4.1.7 on 2023-05-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templates", "0004_remove_template_notification_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="addon_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
