# Generated by Django 5.2.13 on 2026-05-05 07:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0005_template_addon_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="notification_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("EMAIL", "EMAIL"),
                        ("WHATSAPP", "WHATSAPP"),
                        ("SMS", "SMS"),
                    ],
                    default="EMAIL",
                    max_length=50,
                ),
                default=list,
                size=None,
            ),
        ),
    ]
