# Generated by Django 4.1.1 on 2022-09-27 10:34

from django.db import migrations, models
import django.utils.timezone
import unixtimestampfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('EMAIL', 'EMAIL')], default='EMAIL', max_length=100)),
                ('metadata', models.JSONField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True, default=django.utils.timezone.now)),
                ('modified_on', unixtimestampfield.fields.UnixTimeStampField(auto_now=True, default=django.utils.timezone.now)),
                ('created_by', models.UUIDField()),
                ('modified_by', models.UUIDField()),
            ],
            options={
                'db_table': 'configurations',
            },
        ),
    ]
