# Generated by Django 4.1.6 on 2023-02-21 05:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="configuration",
            old_name="config_type",
            new_name="notification_type",
        ),
    ]
