# Generated by Django 4.1.1 on 2022-09-27 11:12

from django.db import migrations, models
import django.utils.timezone
import unixtimestampfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('EMAIL', 'EMAIL')], default='EMAIL', max_length=100)),
                ('status', models.CharField(choices=[('QUEUED', 'QUEUED'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], default='QUEUED', max_length=100)),
                ('metadata', models.JSONField()),
                ('created_on', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True, default=django.utils.timezone.now)),
                ('created_by', models.UUIDField()),
            ],
            options={
                'db_table': 'notification_logs',
            },
        ),
    ]
