# Generated by Django 4.1.1 on 2022-09-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='created_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='modified_by',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
