# Generated by Django 4.1.1 on 2022-09-27 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='type',
            new_name='config_type',
        ),
        migrations.RenameField(
            model_name='notificationlog',
            old_name='entity_type',
            new_name='notification_type',
        ),
    ]
