# Generated by Django 4.1.7 on 2023-05-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_rename_config_type_configuration_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="provider",
            field=models.CharField(
                choices=[("LOCAL_EMAIL", "LOCAL_EMAIL")],
                default="LOCAL_EMAIL",
                max_length=100,
            ),
        ),
    ]
