# Generated by Django 4.1.7 on 2023-05-01 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_alter_configuration_provider"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificationlog",
            name="notification_type",
        ),
        migrations.RemoveField(
            model_name="notificationlog",
            name="tenant",
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="notification_ref",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_logs",
                to="notifications.configuration",
            ),
            preserve_default=False,
        ),
    ]
