# Generated by Django 4.1.7 on 2023-05-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_remove_notificationlog_notification_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
