# Generated by Django 5.2.13 on 2026-05-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0007_alter_configuration_notification_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "QUEUED"),
                    ("PROCESSING", "PROCESSING"),
                    ("SUCCESS", "SUCCESS"),
                    ("FAILED", "FAILED"),
                ],
                default="QUEUED",
                max_length=100,
            ),
        ),
    ]
