# Generated by Django 6.0.6 on 2026-07-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0011_alter_configuration_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("SMTP_EMAIL", "SMTP_EMAIL"),
                            ("LOCAL_EMAIL", "LOCAL_EMAIL"),
                            ("SENDGRID", "SENDGRID"),
                            ("ELASTIC_EMAIL", "ELASTIC_EMAIL"),
                            ("MAILCHIMP", "MAILCHIMP"),
                            ("AWS_SES", "AWS_SES"),
                            ("MAILTRAP", "MAILTRAP"),
                            ("BREVO", "BREVO"),
                            ("MAILGUN", "MAILGUN"),
                            ("POSTMARK", "POSTMARK"),
                            ("SENDPULSE", "SENDPULSE"),
                            ("SAMPLE_EMAIL", "SAMPLE_EMAIL"),
                            ("INTERAKT", "INTERAKT"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "integration_states",
            },
        ),
        migrations.AlterField(
            model_name="configuration",
            name="provider",
            field=models.CharField(
                choices=[
                    ("SMTP_EMAIL", "SMTP_EMAIL"),
                    ("LOCAL_EMAIL", "LOCAL_EMAIL"),
                    ("SENDGRID", "SENDGRID"),
                    ("ELASTIC_EMAIL", "ELASTIC_EMAIL"),
                    ("MAILCHIMP", "MAILCHIMP"),
                    ("AWS_SES", "AWS_SES"),
                    ("MAILTRAP", "MAILTRAP"),
                    ("BREVO", "BREVO"),
                    ("MAILGUN", "MAILGUN"),
                    ("POSTMARK", "POSTMARK"),
                    ("SENDPULSE", "SENDPULSE"),
                    ("SAMPLE_EMAIL", "SAMPLE_EMAIL"),
                    ("INTERAKT", "INTERAKT"),
                ],
                default="SMTP_EMAIL",
                max_length=100,
            ),
        ),
    ]
