# Generated by Django 6.0.6 on 2026-07-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0013_enable_smtp_email_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="provider",
            field=models.CharField(default="SMTP_EMAIL", max_length=100),
        ),
        migrations.AlterField(
            model_name="integrationstate",
            name="provider",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
